language: objective-c
osx_image: xcode7
before_install:
      - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
    - xcodebuild -project Persist.xcodeproj -scheme Persist-OSX test | xcpretty -c
